### ISSUE TITLE
First Feedback and suggestion of exit-report for aborted runs (e.g. for small datasets/no transcripts found)

### ISSUE THREAD

**Issue by e-fuhrmann** [DepledgeLab/NAGATA#1]
Hey there!
First of all, this is some awesome program!
I have used NAGATA for a bit now and feel very positive with the experience.

I'd like to give some Quality of Life-suggestions though:

When using smaller datasets (or data-sets with e.g. a small reverse-read sub-dataset) and NAGATA doesn't find any valid transcripts under the given parameters, instead of breaking it throws an error.

This results in
- uncertainty about what exactly happened
- NAGATA not generating the 'Filtering-counts.txt'-summary-output (although .bed/.gff3-files may have been generated)

Suggestions to improve this:
- Properly exit when no transcripts were found
- give information about the step at which the filtering could no longer continue (helps finding the bottleneck in own data)
- give a short automated suggestion, which parameter(s) may influence this / could be changed to filter ones data properly

But apart from this, NAGATA works quite fast and smoothly for me. The results are continuously looking good.

Many greetings,

~E

**Comment by DepledgeLab** [comment]
resolved
