### ISSUE TITLE
Some first feedback and suggestions regarding the documentation (more parameter-explanation, tmp-file-column-explanation)

### ISSUE THREAD

**Issue by e-fuhrmann** [DepledgeLab/NAGATA#2]
Hi there!

Some suggestions regarding the documentation:
Most parameters are either self explanatory or are explained in the documentation, but I think some additions for some parameters would be nice:
- e.g. it's unclear to me, what exactly the parameter '-a' is doing (TSS abundance per transcription unit (default: 0.1); what exactly is the meaning of the value here?)
- How do changes of certain parameters effect the result?
- Some words on what reasonable value ranges for certain parameters may be
	- e.g. is an increase from -b = 3 to -b = 5 a lot? or to -b = 20?; Obviously this is heavily depended on your own sequencing depth, genome etc. But maybe some examples could help.
- A short explanation of the meaning of (some of) the columns from the tmp-files. Understanding how NAGATA has worked with your data my be important to a successful analysis, so this might be helpful.
- (something really really nitpicky: The README-file has a typo at 'NAGATA outputs'->(1): 'strand' misses the first apostrophe. ->(5) has a lone 'which' at the end in the explanation. '(5) Final_cluster.precollapsed.'strand'.tsv' is listed as an output here but isn't in the actual output)

Generally though the explanations for -t/-c/-tg/-cg-usage is really well done, the visuals help a lot.

Many greetings,

~E

**Comment by DepledgeLab** [comment]
resolved
