### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rebeelouise** [DepledgeLab/NAGATA#4]
Really useful tool!!!

Would this work with direct cDNA as well?

**Comment by DepledgeLab** [comment]
Thank you :)

We never formally tested it with the direct cDNA approach but I don't see any reason why it wouldn't work. You would need to omit the -n flag (as you won't have a nanopolish file) and this may lead to some artefact CPAS escaping the filtering steps. I would expect these to be low abundance however and it should be possible to identify these quite easily after that fact.

If you have any specific issues with the analysis then please do let us know and we will try to resolve them

**Comment by rebeelouise** [comment]
> Thank you :)
> 
> We never formally tested it with the direct cDNA approach but I don't see any reason why it wouldn't work. You would need to omit the -n flag (as you won't have a nanopolish file) and this may lead to some artefact CPAS escaping the filtering steps. I would expect these to be low abundance however and it should be possible to identify these quite easily after that fact.
> 
> If you have any specific issues with the analysis then please do let us know and we will try to resolve them

Excellent, I will give it a go - thank you so much!
